//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteIt.ServiceMantenedorCliente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorCliente.WebServiceMantenedorClienteSoap")]
    public interface WebServiceMantenedorClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webGuardarCliente(NoteIt.ServiceMantenedorCliente.Transacciones transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webGuardarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task webGuardarClienteAsync(NoteIt.ServiceMantenedorCliente.Transacciones transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webEliminarCliente(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task webEliminarClienteAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webActualizarCliente(NoteIt.ServiceMantenedorCliente.Transacciones transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webActualizarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task webActualizarClienteAsync(NoteIt.ServiceMantenedorCliente.Transacciones transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NoteIt.ServiceMantenedorCliente.Transacciones webBuscarCliente(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webBuscarClienteAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarTarea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NoteIt.ServiceMantenedorCliente.Transacciones webBuscarTarea(string titulo_tareas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarTarea", ReplyAction="*")]
        System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webBuscarTareaAsync(string titulo_tareas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarLibreta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NoteIt.ServiceMantenedorCliente.Transacciones webBuscarLibreta(string titulo_libretas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webBuscarLibreta", ReplyAction="*")]
        System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webBuscarLibretaAsync(string titulo_libretas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NoteIt.ServiceMantenedorCliente.Transacciones webPosicionCliente(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webPosicionClienteAsync(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionLibretas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NoteIt.ServiceMantenedorCliente.Transacciones webPosicionLibretas(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionLibretas", ReplyAction="*")]
        System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webPosicionLibretasAsync(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionTareas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NoteIt.ServiceMantenedorCliente.Transacciones webPosicionTareas(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webPosicionTareas", ReplyAction="*")]
        System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webPosicionTareasAsync(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webRetornarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webRetornarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webRetornarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webRetornarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webRetornarLibretas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webRetornarLibretas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webRetornarLibretas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webRetornarLibretasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webRetornarTareas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webRetornarTareas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webRetornarTareas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webRetornarTareasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAgregarTarea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webAgregarTarea(NoteIt.ServiceMantenedorCliente.Transacciones transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAgregarTarea", ReplyAction="*")]
        System.Threading.Tasks.Task webAgregarTareaAsync(NoteIt.ServiceMantenedorCliente.Transacciones transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAgregarLibreta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webAgregarLibreta(NoteIt.ServiceMantenedorCliente.Transacciones transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webAgregarLibreta", ReplyAction="*")]
        System.Threading.Tasks.Task webAgregarLibretaAsync(NoteIt.ServiceMantenedorCliente.Transacciones transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarTareas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webListarTareas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarTareas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webListarTareasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarLibretas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet webListarLibretas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webListarLibretas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> webListarLibretasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarTarea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webEliminarTarea(string titulo_tareas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarTarea", ReplyAction="*")]
        System.Threading.Tasks.Task webEliminarTareaAsync(string titulo_tareas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarLibreta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void webEliminarLibreta(string titulo_libretas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webEliminarLibreta", ReplyAction="*")]
        System.Threading.Tasks.Task webEliminarLibretaAsync(string titulo_libretas);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transacciones : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string nombreField;
        
        private string tareasField;
        
        private string libretasField;
        
        private string titulo_tareasField;
        
        private string titulo_libretasField;
        
        private System.DateTime fecha_tareasField;
        
        private System.DateTime fecha_libretasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Tareas {
            get {
                return this.tareasField;
            }
            set {
                this.tareasField = value;
                this.RaisePropertyChanged("Tareas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Libretas {
            get {
                return this.libretasField;
            }
            set {
                this.libretasField = value;
                this.RaisePropertyChanged("Libretas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Titulo_tareas {
            get {
                return this.titulo_tareasField;
            }
            set {
                this.titulo_tareasField = value;
                this.RaisePropertyChanged("Titulo_tareas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Titulo_libretas {
            get {
                return this.titulo_libretasField;
            }
            set {
                this.titulo_libretasField = value;
                this.RaisePropertyChanged("Titulo_libretas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime Fecha_tareas {
            get {
                return this.fecha_tareasField;
            }
            set {
                this.fecha_tareasField = value;
                this.RaisePropertyChanged("Fecha_tareas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime Fecha_libretas {
            get {
                return this.fecha_libretasField;
            }
            set {
                this.fecha_libretasField = value;
                this.RaisePropertyChanged("Fecha_libretas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMantenedorClienteSoapChannel : NoteIt.ServiceMantenedorCliente.WebServiceMantenedorClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMantenedorClienteSoapClient : System.ServiceModel.ClientBase<NoteIt.ServiceMantenedorCliente.WebServiceMantenedorClienteSoap>, NoteIt.ServiceMantenedorCliente.WebServiceMantenedorClienteSoap {
        
        public WebServiceMantenedorClienteSoapClient() {
        }
        
        public WebServiceMantenedorClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMantenedorClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMantenedorClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void webGuardarCliente(NoteIt.ServiceMantenedorCliente.Transacciones transacciones) {
            base.Channel.webGuardarCliente(transacciones);
        }
        
        public System.Threading.Tasks.Task webGuardarClienteAsync(NoteIt.ServiceMantenedorCliente.Transacciones transacciones) {
            return base.Channel.webGuardarClienteAsync(transacciones);
        }
        
        public void webEliminarCliente(string rut) {
            base.Channel.webEliminarCliente(rut);
        }
        
        public System.Threading.Tasks.Task webEliminarClienteAsync(string rut) {
            return base.Channel.webEliminarClienteAsync(rut);
        }
        
        public void webActualizarCliente(NoteIt.ServiceMantenedorCliente.Transacciones transacciones) {
            base.Channel.webActualizarCliente(transacciones);
        }
        
        public System.Threading.Tasks.Task webActualizarClienteAsync(NoteIt.ServiceMantenedorCliente.Transacciones transacciones) {
            return base.Channel.webActualizarClienteAsync(transacciones);
        }
        
        public System.Data.DataSet webListarCliente() {
            return base.Channel.webListarCliente();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webListarClienteAsync() {
            return base.Channel.webListarClienteAsync();
        }
        
        public NoteIt.ServiceMantenedorCliente.Transacciones webBuscarCliente(string rut) {
            return base.Channel.webBuscarCliente(rut);
        }
        
        public System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webBuscarClienteAsync(string rut) {
            return base.Channel.webBuscarClienteAsync(rut);
        }
        
        public NoteIt.ServiceMantenedorCliente.Transacciones webBuscarTarea(string titulo_tareas) {
            return base.Channel.webBuscarTarea(titulo_tareas);
        }
        
        public System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webBuscarTareaAsync(string titulo_tareas) {
            return base.Channel.webBuscarTareaAsync(titulo_tareas);
        }
        
        public NoteIt.ServiceMantenedorCliente.Transacciones webBuscarLibreta(string titulo_libretas) {
            return base.Channel.webBuscarLibreta(titulo_libretas);
        }
        
        public System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webBuscarLibretaAsync(string titulo_libretas) {
            return base.Channel.webBuscarLibretaAsync(titulo_libretas);
        }
        
        public NoteIt.ServiceMantenedorCliente.Transacciones webPosicionCliente(int fila) {
            return base.Channel.webPosicionCliente(fila);
        }
        
        public System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webPosicionClienteAsync(int fila) {
            return base.Channel.webPosicionClienteAsync(fila);
        }
        
        public NoteIt.ServiceMantenedorCliente.Transacciones webPosicionLibretas(int fila) {
            return base.Channel.webPosicionLibretas(fila);
        }
        
        public System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webPosicionLibretasAsync(int fila) {
            return base.Channel.webPosicionLibretasAsync(fila);
        }
        
        public NoteIt.ServiceMantenedorCliente.Transacciones webPosicionTareas(int fila) {
            return base.Channel.webPosicionTareas(fila);
        }
        
        public System.Threading.Tasks.Task<NoteIt.ServiceMantenedorCliente.Transacciones> webPosicionTareasAsync(int fila) {
            return base.Channel.webPosicionTareasAsync(fila);
        }
        
        public System.Data.DataSet webRetornarCliente() {
            return base.Channel.webRetornarCliente();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webRetornarClienteAsync() {
            return base.Channel.webRetornarClienteAsync();
        }
        
        public System.Data.DataSet webRetornarLibretas() {
            return base.Channel.webRetornarLibretas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webRetornarLibretasAsync() {
            return base.Channel.webRetornarLibretasAsync();
        }
        
        public System.Data.DataSet webRetornarTareas() {
            return base.Channel.webRetornarTareas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webRetornarTareasAsync() {
            return base.Channel.webRetornarTareasAsync();
        }
        
        public void webAgregarTarea(NoteIt.ServiceMantenedorCliente.Transacciones transacciones) {
            base.Channel.webAgregarTarea(transacciones);
        }
        
        public System.Threading.Tasks.Task webAgregarTareaAsync(NoteIt.ServiceMantenedorCliente.Transacciones transacciones) {
            return base.Channel.webAgregarTareaAsync(transacciones);
        }
        
        public void webAgregarLibreta(NoteIt.ServiceMantenedorCliente.Transacciones transacciones) {
            base.Channel.webAgregarLibreta(transacciones);
        }
        
        public System.Threading.Tasks.Task webAgregarLibretaAsync(NoteIt.ServiceMantenedorCliente.Transacciones transacciones) {
            return base.Channel.webAgregarLibretaAsync(transacciones);
        }
        
        public System.Data.DataSet webListarTareas() {
            return base.Channel.webListarTareas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webListarTareasAsync() {
            return base.Channel.webListarTareasAsync();
        }
        
        public System.Data.DataSet webListarLibretas() {
            return base.Channel.webListarLibretas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> webListarLibretasAsync() {
            return base.Channel.webListarLibretasAsync();
        }
        
        public void webEliminarTarea(string titulo_tareas) {
            base.Channel.webEliminarTarea(titulo_tareas);
        }
        
        public System.Threading.Tasks.Task webEliminarTareaAsync(string titulo_tareas) {
            return base.Channel.webEliminarTareaAsync(titulo_tareas);
        }
        
        public void webEliminarLibreta(string titulo_libretas) {
            base.Channel.webEliminarLibreta(titulo_libretas);
        }
        
        public System.Threading.Tasks.Task webEliminarLibretaAsync(string titulo_libretas) {
            return base.Channel.webEliminarLibretaAsync(titulo_libretas);
        }
    }
}
